name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Homework test
      id: homework-test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 13
        setup-command: pip install import-ipynb openpyxl numpy matplotlib pandas==2.1.3
          seaborn
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HOMEWORK-TEST_RESULTS: "${{steps.homework-test.outputs.result}}"
      with:
        runners: homework-test
